---
- name: software setup
  hosts: localhost
  become: yes
  tasks:
    - import_role:
       name: common
    - include_role:
       name: aur_module
    - include_role:
       name: gpib
    - include_role:
       name: visa
    - include_role:
       name: hdf5
    - include_role:
       name: control-software
