---
- name: install java
  pacman:
    name: ['jdk-openjdk']

- name: make sure java is OpenJDK 11
  shell: archlinux-java set java-11-openjdk

- name: install hdf5 with java
  become: yes
  become_user: aur_builder
  environment:
    PKGDEST: ""
  aur:
    name: ['hdf5-java', 'hdfview', 'python-h5py']
