---
- name: install pyserial
  ignore_errors: yes
  pacman:
    name: ['python-pyserial' 'python-numpy']
    state: present

#- name: install mutovis control-software
#  become: yes
#  become_user: aur_builder
#  environment:
#    PKGDEST: ""
#  aur:
#    name: ['mutovis-control-software']
