---
- name: install control software
  become: yes
  become_user: aur_builder
  environment:
    PKGDEST: ""
  aur:
    name: ['python-mutovis-control']

- name: use our gpib.conf
  file:
    src: /usr/etc/gpib.conf
    dest: /etc/gpib.conf
    state: link
    force: yes
