---
- name: remove wrong pyvisa packages
  ignore_errors: yes
  pacman:
    name: python-pyvisa-git
    state: absent

- name: remove wrong pyvisa-py package
  ignore_errors: yes
  pacman:
    name: python-pyvisa-py
    state: absent

- name: install pyvisa
  become: yes
  become_user: aur_builder
  environment:
    PKGDEST: ""
  aur:
    name: ['python-pyvisa','python-pyvisa-py-git']
