---
- name: Get the kernel version
  command: "uname -r"
  register: uname

- name: full system upgrade
  pacman:
    update_cache: yes
    upgrade: yes

- name: install git and base devel group
  pacman:
    name: ['base-devel', 'git']

- name: make AUR build dir
  file:
    path: /home/build
    state: directory
    group: nobody
    mode: "g+ws"

- name: get ready to build from AUR
  shell: |
    setfacl -m u::rwx,g::rwx /home/build
    setfacl -d --set u::rwx,g::rwx,o::- /home/build
    
    exit 0
    
- git:
    repo: 'https://aur.archlinux.org/ansible-aur-git.git'
    dest: /home/build/ansible-aur-git
    force: yes
    
- name: remove packages
  file:
    path: /home/build/ansible-aur-git/*.pkg.tar
    state: absent
  
- name: build ansible AUR module
  command: "makepkg"
  environment:
    PKGEXT: .pkg.tar
  args:
    chdir: /home/build/ansible-aur-git
  become: yes
  become_user: nobody

- name: install ansible AUR module
  shell: "pacman -U *.pkg.tar"
  args:
    chdir: /home/build/ansible-aur-git
