---
- name: Get the kernel version
  command: "uname -r"
  register: uname
- name: full system upgrade
  pacman:
    update_cache: yes
    upgrade: yes
- name: install git and base devel group
  pacman:
    name: ['base-devel', 'git']
