---
- name: Get the kernel version
  command: "uname -r"
  register: uname

- name: full system upgrade
  pacman:
    update_cache: yes
    upgrade: yes

- name: install git and base devel group
  pacman:
    name: ['base-devel', 'git', 'sudo']

- name: make AUR build dir
  file:
    path: /home/build
    state: directory
    group: nobody
    mode: "g+ws"

- name: get ready to build from AUR
  shell: |
    setfacl -m u::rwx,g::rwx /home/build
    setfacl -d --set u::rwx,g::rwx,o::- /home/build
    
    exit 0
    
- git:
    repo: 'https://aur.archlinux.org/ansible-aur-git.git'
    dest: /home/build/ansible-aur-git
  
- name: build ansible AUR module
  command: "sudo -u nobody makepkg -i"
  args:
    chdir: /home/build/ansible-aur-git
