---
- name: install linux-gpib kernel module and python bindings
  become: yes
  become_user: aur_builder
  environment:
    PKGDEST: ""
  aur:
#    name: ['linux-gpib-dkms','python-linux-gpib','fxload']
# for now, we need to use linux-gpib-svn because the stable release doesn't support linux 5
    name: ['linux-gpib-svn','fxload']

- name: ni_usb_gpib kernel module to be loaded at boot
  copy:
    content: "ni_usb_gpib"
    dest: /etc/modules-load.d/gpib.conf
    force: yes

