---
- name: install linux-gpib kernel module and python bindings
  become: yes
  become_user: aur_builder
  environment:
    PKGDEST: ""
  aur:
    name: ['linux-gpib-dkms','python-linux-gpib','fxload']
