---
- name: install arduino-cli
  pacman:
    name: arduino-cli
    state: present

- name: clone firmware repo
  become: yes
  become_user: mutovis
  git:
    repo: 'https://github.com/mutovis/firmware.git'
    dest: /home/mutovis/git/mutovis/firmware
    version: master

- name: setup arduino-cli
  become: yes
  become_user: mutovis
  shell: |
     arduino-cli core update-index
     arduino-cli core install arduino:avr
     arduino-cli lib install "Ethernet"
     exit 0

- name: find arduino tmp files
  find:
    paths: /tmp
    file_type: directory
    patterns: arduino-*
  register: ard_tmp_dirs

- name: clean arduino tmp
  file:
    state: absent
    path: "{{ item.path }}"
  with_items: "{{ ard_tmp_dirs.files }}"

- name: compile firmware
  become: yes
  become_user: mutovis
  args:
    chdir: /home/mutovis/git/mutovis/firmware/mainArduino
  shell: bash compile.sh
